# https://starship.rs/config/

# Don't print a new line at the start of the prompt
# add_newline = false

# [line_break]
# disabled = true

[character]
# Replace the "â¯" symbol in the prompt with "âœ"
# symbol = "âœ"

[git_branch]
# symbol = ""
# style = "purple"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
# displayed_items = "profile"

[aws.region_aliases]
ap-southeast-2 = "aws-au"

[battery]
disabled = true

[directory]
truncation_length = 8
truncate_to_repo = false

[lua]
disabled = true

[memory_usage]
disabled = false
threshold = -1
style = "bold dimmed white"
format = "[RAM:${ram_pct}(|SWP:${swap_pct})]($style) "

[python]
disabled = true
pyenv_version_name = true
style = "yellow"

[php]
style = "red"

[nodejs]
# style = "green"
symbol = "N "
disabled = true

[docker_context]
disabled = true

[vagrant]
disabled = true

[ruby]
disabled = true
symbol = "R "


[git_status]
disabled = true
format = '([\[$conflicted$stashed$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style) )'

# conflicted = "ğŸ³"
# ahead = "ğŸğŸ’¨"
# behind = "ğŸ˜°"
# diverged = "ğŸ˜µ"
# untracked = "ğŸ¤·â€"
# stashed = "ğŸ“¦"
# modified = "ğŸ“"
# staged = '[++\($count\)](green)'
# renamed = "ğŸ‘…"
# deleted = "ğŸ—‘"

[time]
disabled = false
# style = "yellow"
# format = "[%T]"
